name: this blog is girtby.net
url: http://girtby.net
markdown: redcarpet
highlighter: pygments
paginate: 10
paginate_path: "page/:num"
permalink: /archives/:year/:month/:day/:title/
category_dir: /archives/category
archive_dir: /archives
# plugins:
#   #- jekyll-redirect-from
#   - jekyll-sitemap
#   - jekyll-paginate
#   - jekyll-oembed
# flicrk:
#   api_key: 
